# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Fcntl_Lock
version:      0.08
version_from: lib/File/Fcntl_Lock.pm
installdirs:  site
requires:
    Carp:                          0
    DynaLoader:                    0
    Errno:                         0
    Exporter:                      0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
